% This compile.m is used under Windows
clc;
clear mex
fprintf('Compiling SI-UNIWARD ... ');

%% 64 bit Windows and Matlab
mex -O -largeArrayDims -output SI_UNIWARD ...
    -I../include ...
    SI-UNIWARD_matlab.cpp ...
    cost_model_config.cpp ... 
    cost_model.cpp ...    
    ../include/base_cost_model.cpp ...
    ../include/base_cost_model_config.cpp ...
    ../include/mi_embedder.cpp ...
    ../include/stc_ml_c.cpp ...
    ../include/stc_embed_c.cpp ...
    ../include/stc_extract_c.cpp ...
    ../include/common.cpp ...
    ../include/image.cpp ...
    ../include/jstruct.cpp ...
    ../include/info_theory.cpp ...
    -L../lib ...
    -llibjpeg

fprintf('DONE\n');
clear mex
movefile('*.mex*','../matlab/matlab_MEX');
fprintf('\nCompiled SI-UNIWARD MEX file was moved to ../matlab/matlab_MEX folder.\n');
